# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{ github.workspace }}
#             ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports

        - name: Upload test results
          if: success() || failure()
          uses: actions/upload-artifact@v2
          with:
            name: test-results
            path: __tests__/__results__/*.xml

        - name: Create test report 01
          uses: ./
          if: success() || failure()
          with:
            name: JEST Tests
            path: __tests__/__results__/*.xml
            reporter: jest-junit

#         - name: Upload test results
#           uses: actions/upload-artifact@v1
#           if: always()
#           with:
#             name: reports
#             path: ${{ github.workspace }}
            
 
