name: World Greeter
on:
  push:
    branches: [ main, master, staging ]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Say World
        run: echo "World"
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - job-1
#       - job-2
    runs-on: ubuntu-latest
    steps:
      - uses: voxmedia/github-action-slack-notify-build@v1
        with:
            channel: app-alerts
            status: STARTED
            color: good
        env:
            SLACK_BOT_TOKEN: xoxb-2295795949815-2310727261731-NZtRIHCgHZC3LF6hcElJmIKm
