name: World Greeter
on:
  push:
    branches: [main, master, staging ]
jobs:
  test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{ github.workspace }}
#             ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Say World
        run: echo "World"
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - test
#       - job-2
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: '#testing'
          name: 'Anthony Workflow Bot'
          icon_emoji: ':octocat:'
          icon_url: 'https://avatars0.githubusercontent.com/u/1701160?s=96&v=4'
    
          
  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: test
    runs-on: ubuntu-latest
    # the build-and-test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/*.xml

#   slack-notfi01:
#     name: Slack Notification 01
#     runs-on: ubuntu-latest
#     steps:
#         - uses: actions/checkout@v2
#         - name: Slack Notification
#           uses: rtCamp/action-slack-notify@v2
#           env:
#             SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL}}
#         - name: Slack Notification 02
#           uses: rtCamp/action-slack-notify@v2
#           env:
#             SLACK_CHANNEL: '#testing'
#             SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#             SLACK_ICON: https://github.com/rtCamp.png?size=48
#             SLACK_MESSAGE: 'Post Content :rocket:'
#             SLACK_TITLE: Post Title
#             SLACK_USERNAME: rtCamp
#             SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL}}
#       - name: slack-workflow-result
#         uses: SynergiTech/slack-workflow-result@v1
#         with:
#           status: ${{ job.status }}
#           author_name: Integration Test # default: 8398a7@action-slack
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
#         if: always() # Pick up events even if the job fails or is canceled.
